[tool.poetry]
name = "thetagang"
version = "0.1.0"
description = "ThetaGang is an IBKR bot for getting money"
authors = ["Brenden Matthews <brenden@brndn.io>"]
license = "AGPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.9"
ib_insync = "^0.9.64"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
